name: Test page
favicon: null
layout_spectrum: 1
typography_spectrum: 0.17248
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbffff'
    - '#101113'
    - '#708540'
    - '#a995b0'
    - '#855144'
  brandStrength: 0.22432464826852083
  lightness: 0.75
  saturation: 0.5475127215031534
  rhythmicContrast: 0.25
purpose: []
