name: 'Barátom, az AI'
favicon: null
layout_spectrum: 0.63187
typography_spectrum: 0.17248
title: 'Barátom, az AI'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a0d07'
    - '#fffffd'
    - '#5589b8'
    - '#94c9e9'
    - '#fa522d'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
