name: Test page
favicon: null
layout_spectrum: 0.20865
typography_spectrum: 0.17248
title: 'Barátom, az AI'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a0d07'
    - '#fffffd'
    - '#5589b8'
    - '#94c9e9'
    - '#fa522d'
  brandStrength: 0.0625
  lightness: 0.9375
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
